export enum TaskType {
  CREATE_GOOGLE_USER = 'CREATE_GOOGLE_USER',
  ADD_GOOGLE_GROUPS = 'ADD_GOOGLE_GROUPS',
  CONFIGURE_GMAIL_SIGNATURE = 'CONFIGURE_GMAIL_SIGNATURE',
  SEND_WELCOME_EMAIL = 'SEND_WELCOME_EMAIL',
  ANNOUNCE_IN_GROUPS = 'ANNOUNCE_IN_GROUPS',
  POST_INTERNAL_ANNOUNCEMENT = 'POST_INTERNAL_ANNOUNCEMENT',
  REQUEST_DEVICE = 'REQUEST_DEVICE',
  NOTIFY_ADMINISTRATION = 'NOTIFY_ADMINISTRATION',
}
